import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import style from './unread.css';
import { FaFacebook, FaInstagram, FaTwitter, FaLinkedinIn, FaSearch } from "react-icons/fa";
import Header from "@/componets/layout/header";
import Footer from "@/componets/layout/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
      <Header/>
        <div className="BackgroundImg">
         <Image className="BackgroundImg" src={"/images/background img.jpg"} alt="background image" width={500} height={500}/>
        </div>
        <div className="overLay"></div>
        <div className="heroOverlay">
          {/* <Image className="overlayImg" src={"/images/heroimg.jpg"} alt="img" width={100} height={100}/> */}
        </div>
      <Footer />
      </body>
    </html>
  );
}
